spring:
  redis:
    password: UoQzC2WjHm1y   # 密码（默认为空）
    timeout: 60000  # 连接超时时长（毫秒）ms
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）ms
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 3       # 连接池中的最小空闲连接
        max-attempts: 5   # 重试次数
        test-on-borrow: true # 是否在从池中取出连接前进行检验,如果检验失败,则从池中去除连接并尝试取出另一个
  standalone:
    database: 0
    host: 120.55.242.68
    port: 20024
    password: UoQzC2WjHm1y   # 密码（默认为空）
    timeout: 60000  # 连接超时时长（毫秒）ms