# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 18086
  connection-timeout: 5000ms
  servlet:
    context-path: /datahub-to-tablestore

spring:
  # 环境 dev|test|prod
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  mvc:
    throw-exception-if-no-handler-found: true
app:
  id: ywclj
apollo:
  meta: http://120.55.242.68:18083

logging:
  config: classpath:logging-config.xml